/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
    *(volatile uint32_t *) 0x40023830 |= (1 << 0); // Enable GPIOA clock

    *(volatile uint32_t *) 0x40020000 &= ~(3 << 10); // Clear mode bits for PA5

    *(volatile uint32_t *) 0x40020000 |= (1 << 10); // Set PA5 as output

    *(volatile uint32_t *) 0x40020014 |= (1 << 5); // Set PA5 high

    while(1)
    {
    	;
    }
}
