/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
	volatile uint32_t * RCC = (volatile uint32_t *) 0x40023830; // RCC_AHB1ENR address

	volatile uint32_t * GPIOA_MODER = (volatile uint32_t *) 0x40020000; // GPIOA_MODER register address

	volatile uint32_t * GPIOA_ODR = (volatile uint32_t *) 0x40020014; // GPIOA_ODR register address

	volatile uint32_t * GPIOA_IDR = (volatile uint32_t *) 0x40020010; // GPIOA_IDR register address

    *RCC |= (1 << 0); // Enable GPIOA clock

    *GPIOA_MODER &= ~(3 << 0); // Clear mode bits for PA0

    *GPIOA_MODER |= (0<<0); // Set PA0 as input

    *GPIOA_MODER &= ~(3 << 10); // Clear mode bits for PA5

    *GPIOA_MODER |= (1 << 10); // Set PA5 as output


    while(1)
    {
    	if (*GPIOA_IDR & (1 << 0)) // Check if PA0 is high
		{
			*GPIOA_ODR |= (1 << 5); // Set PA5 high

		}
		else
		{
			*GPIOA_ODR &= ~(1 << 5); // Set PA5 low
		}


    }
}
